version: '2.3'
services:
  rain:
    image: onlytailei/carla_cil:pytorch0.4.1-cuda9-oepcv3.4.3-imgaug
    runtime: nvidia
    volumes:
      - /data_shared/Docker/ltai/dataset:/home/dataset
      - /data_shared/Docker/ltai/ws/carla_cil_training:/home/ws/carla_cil_training
    working_dir: /home/ws/carla_cil_training
    cpu_count: 8
    mem_reservation: 10000M
    shm_size: 10000M
    command:
      python main.py
      --batch-size 1000
      --workers 16
      --train-dir "/home/dataset/carla_cil/chosen_weather_train/rainnoon_h5/"
      --eval-dir "/home/dataset/carla_cil/chosen_weather_test/rainnoon_h5/"
      --gpu 0
      --id rain_policy

  wet:
    image: onlytailei/carla_cil:pytorch0.4.1-cuda9-oepcv3.4.3-imgaug
    runtime: nvidia
    volumes:
      - /data_shared/Docker/ltai/dataset:/home/dataset
      - /data_shared/Docker/ltai/ws/carla_cil_training:/home/ws/carla_cil_training
    working_dir: /home/ws/carla_cil_training
    cpu_count: 8
    mem_reservation: 10000M
    shm_size: 10000M
    command:
      python main.py
      --batch-size 1000
      --workers 16
      --train-dir "/home/dataset/carla_cil/chosen_weather_train/wetnoon_h5/"
      --eval-dir "/home/dataset/carla_cil/chosen_weather_test/wetnoon_h5/"
      --gpu 1
      --id wet_policy

  sunset:
    image: onlytailei/carla_cil:pytorch0.4.1-cuda9-oepcv3.4.3-imgaug
    runtime: nvidia
    volumes:
      - /data_shared/Docker/ltai/dataset:/home/dataset
      - /data_shared/Docker/ltai/ws/carla_cil_training:/home/ws/carla_cil_training
    working_dir: /home/ws/carla_cil_training
    cpu_count: 8
    mem_reservation: 10000M
    shm_size: 10000M
    command:
      python main.py
      --batch-size 1000
      --workers 16
      --train-dir "/home/dataset/carla_cil/chosen_weather_train/sunset_h5/"
      --eval-dir "/home/dataset/carla_cil/chosen_weather_test/sunset_h5/"
      --gpu 2
      --id sunset_policy
